#!/bin/sh
#
# /etc/rc: system boot script
#

echo "The system is coming up.  Please wait."

# Load configuration.
. /etc/rc.conf

# Mount virtual filesystems and /run for udevd runtime data.
if ! /bin/mountpoint -q /proc; then
	/bin/mount -n -t proc none /proc
fi

if ! /bin/mountpoint -q /sys; then
	/bin/mount -n -t sysfs none /sys
fi

if ! /bin/mountpoint -q /dev; then
	/bin/mount -n -t devtmpfs -o exec,nosuid,noatime,mode=0755,nr_blocks=2048,nr_inodes=16384 dev /dev
else
	/bin/mount -n -o remount,exec,nosuid,noatime,mode=0755,nr_blocks=2048,nr_inodes=16384 dev /dev
fi

if ! /bin/mountpoint -q /dev/pts; then
	/bin/mkdir -m 0755 /dev/pts
	/bin/mount -n -t devpts -o noexec,nosuid,gid=tty,mode=0620 devpts /dev/pts
fi

if ! /bin/mountpoint -q /dev/shm; then
	/bin/mkdir -m 1777 /dev/shm
	/bin/mount -n -t tmpfs -o defaults,exec,rw shm /dev/shm
fi

if ! /bin/mountpoint -q /run; then
	/bin/mount -n -t tmpfs -i mode=0755,nosuid,nodev,exec tmpfs /run
fi

# Record boot messages.
if [ "$BOOTLOG" ] && [ -x /etc/rc.d/"$BOOTLOG" ]; then
	/etc/rc.d/"$BOOTLOG" start
fi

# Start device manager if specified, otherwise start udevd(8).
if [ "$DEVMGR" ] && [ -x /etc/rc.d/"$DEVMGR" ]; then
	/etc/rc.d/"$DEVMGR" start
else
	# Copy devices from /lib/udev/devices.
	if [ -d /lib/udev/devices ]; then
		/bin/cp -ar /lib/udev/devices/* /dev
	fi

	# Launch udev daemon, make sure it's not running first.
	if ! /bin/pidof -q -s udevd; then
		/sbin/udevd --daemon
	fi

	# Coldplug devices and wait for the queue to be processed.
	/sbin/udevadm trigger --type=subsystems --action=add
	/sbin/udevadm trigger --type=devices    --action=add
	/sbin/udevadm settle
fi

# Create device-mapper device nodes and scan for LVM volume groups.
if [ -x /sbin/lvm ]; then
	/sbin/vgscan --mknodes --ignorelockingfailure
	/sbin/vgchange --sysinit -a y
fi

# Look for devices that could form further arrays and try to assemble them.
if [ -x /sbin/mdadm ]; then
	/sbin/mdadm --assemble --scan
fi

# Map encrypted volumes needed for fsck/fstab.
# Run only non-%random volumes here, since they may be listed in fstab.
if [ -f /etc/crypttab ] && [ -x /sbin/cryptmount ]; then
	/sbin/cryptmount -M -O '!%random'
fi

# Mount root read-only.
/bin/mount -o remount,ro /

# Check filesystems.
if [ -f /forcefsck ]; then
FORCEFSCK="-f"
fi
# Intentional.
# shellcheck disable=SC2086
/sbin/fsck $FORCEFSCK -A -T -C -a
if [ $? -gt 1 ]; then
	echo
	echo "***************  FILESYSTEM CHECK FAILED  ******************"
	echo "*                                                          *"
	echo "*  Please repair manually and reboot. Note that the root   *"
	echo "*  file system is currently mounted read-only. To remount  *"
	echo "*  it read-write type: mount -n -o remount,rw /            *"
	echo "*  When you exit the maintenance shell the system will     *"
	echo "*  reboot automatically.                                   *"
	echo "*                                                          *"
	echo "************************************************************"
	echo
	/sbin/sulogin -p
	echo "Automatic reboot in progress..."
	/bin/umount -a -r
	/bin/mount -o remount,ro /
	/sbin/reboot -f
	exit 0
fi

# Mount local filesystems.
/bin/mount -o remount,rw /
/bin/mount -a -O no_netdev

# Load random seed before handling %random volumes.
if [ -x /sbin/seedrng ]; then
	/sbin/seedrng
fi

# Map %random volumes now that RNG is seeded.
if [ -f /etc/crypttab ] && [ -x /sbin/cryptmount ]; then
	/sbin/cryptmount -M -O '%random'
fi

# Create user runtime directory.
/bin/mkdir -m 0755 /run/user

# Activate swap.
/sbin/swapon -a

# Clean up misc files.
: >/run/utmp
/bin/rm -rf /forcefsck /fastboot /etc/nologin /etc/shutdownpid
(cd /var/lock && /usr/bin/find . ! -type d -delete)
(cd /tmp      && /usr/bin/find . ! -name . -delete)

# ICE sockets (session managers, clipboard)
/bin/mkdir -m 1777 /tmp/.ICE-unix

# X11 sockets (X server/clients)
/bin/mkdir -m 1777 /tmp/.X11-unix

# Set kernel variables.
/sbin/sysctl -p >/dev/null

# Update shared library links.
/sbin/ldconfig

# Set system hostname.
if [ "$HOSTNAME" ]; then
	echo "hostname: $HOSTNAME"
	/bin/hostname "$HOSTNAME"
fi

# Set system timezone.
if [ "$TIMEZONE" ] && [ -f /usr/share/zoneinfo/"$TIMEZONE" ]; then
	/bin/ln -snf /usr/share/zoneinfo/"$TIMEZONE" /etc/localtime
fi

# Set system time from hardware clock.
/sbin/hwclock -s

# Load console font.
if [ "$FONT" ] && [ -x /usr/bin/setfont ]; then
	echo "font: $FONT"
	/usr/bin/setfont "$FONT"
fi

# Load console keymap.
if [ "$KEYMAP" ] && [ -x /usr/bin/loadkeys ]; then
	echo "keyboard: $KEYMAP"
	/usr/bin/loadkeys -q "$KEYMAP"
fi

# Set screen blank timeout.
if [ -x /usr/bin/setterm ]; then
	/usr/bin/setterm -blank "${BLANKTIME:-15}"
fi

# Run module initialization script.
if [ -x /etc/rc.modules ]; then
	/etc/rc.modules
fi

# Save kernel ring buffer.
/bin/dmesg >/var/log/dmesg

# End of file.
